version: '3'
services:
  db:
    image: postgres:12
    env_file:
      - .db.env
    ports:
      - 5433:5433
    volumes:
      - desafio_ninja_db:/var/lib/postgresql/data
  
  app:
    build: .
    container_name: desafio_ninja_rails
    command:  bash start.sh
    ports:
      - 5000:5000
    volumes:
      - '.:/ninja_challenge'
      - bundler_gems:/usr/local/bundle/
    env_file:
      - .db.env
    depends_on:
      - db

volumes:
  desafio_ninja_db:
  bundler_gems:
  db:
